server {
    listen 80;
    server_name localhost;

    # Nginx will try to route these to localhost, but since Nginx is in a container, 
    # we use host.docker.internal to route to our local host machine where Node.js / Next.js will be running initially.
    # Later this will be changed to the docker container names (e.g., http://backend:1337).

    location /api/ {
        proxy_pass http://backend:1337/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location / {
        proxy_pass http://frontend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
